# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/PyCQA/pylint
    rev: v2.15.6
    hooks:
      - id: pylint
        language: system
        args:
          - --output-format=colorized
          - --errors-only
          - --rcfile=src/.pylintrc
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest src/tests/unit
        language: system
        pass_filenames: false
        always_run: true
