mysql:
  auth:
    database: shopapp
    username: shopapp
  secondary:
    replicaCount: 1
  initdbScripts:
    my_init_script.sh: |
      #!/bin/sh
       mysql -P 3306 -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e "CREATE TABLE IF NOT EXISTS user (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(100) UNIQUE NOT NULL, password VARCHAR(200) NOT NULL);"
       mysql -P 3306 -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e "CREATE TABLE IF NOT EXISTS products (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(30),price INT);"
       mysql -P 3306 -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e "INSERT INTO products (name, price) VALUES ('Hammer', 199), ('Nail', 99), ('Screwdriver', 79);"

shopapp:
  replicas: 1
  image: ghcr.io/ppaslan/devops21_cicd_final/shopapp:1.0.7
  regCredSecretName: repcred
  imagePullPolicy: IfNotPresent
  serviceType: ClusterIP
  config:
    MYSQL_USER: shopapp
    MYSQL_DATABASE: shopapp
