---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shop-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ppaslan/devops21_cicd_final.git
    targetRevision: main
    path: instances/shop-production
  destination:
    server: https://kubernetes.default.svc
    namespace: shop-production
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
