---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}-config
data:
{{ toYaml .Values.config | indent 4 }}
    MYSQL_HOST: {{ .Release.Name }}-mysql.{{ .Release.Namespace }}.svc.cluster.local
